[build]
  publish = "."            # static site in repo root
  command = ""             # no build step
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["cheerio", "pdf-lib"]
  included_files = []

[build.environment]
  NODE_VERSION = "18"
